name: ale
channels:
  - mechsoft
  - local
  - conda-forge
  - default

dependencies:
  - cmake>=3.15
  - cspice ==66
  - pytest
  - eigen
  - jupyter
  - nlohmann_json
  - numpy
  - pvl
  - pytz
  - python
  - python-dateutil
  - scipy
  - spiceypy>=2.3.0
  - pyyaml
  - networkx
